[general]
columns = ['image_id', 'id', 'category', 'category_topology',
           'category_mode', 'visible_energy', 'leading_muon_ke', 'leading_proton_ke', 'leading_muon_pt',
           'leading_proton_pt', 'interaction_pt', 'leading_muon_cosine_theta_xz',
           'leading_proton_cosine_theta_xz', 'cosine_opening_angle', 'cosine_opening_angle_transverse',
           'leading_muon_softmax', 'leading_proton_softmax']
cv_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_cv.log'

[general.variables]
visible_energy = [25, 0, 3000]
interaction_pt = [25, 0, 1200]
leading_muon_ke = [25, 0, 2000]
leading_proton_ke = [25, 0, 600]
leading_muon_pt = [25, 0, 750]
leading_proton_pt = [25, 0, 750]
leading_muon_cosine_theta_xz = [25, -1, 1]
leading_proton_cosine_theta_xz = [25, -1, 1]
cosine_opening_angle = [25, -1, 1]
cosine_opening_angle_transverse = [25, -1, 1]
leading_muon_softmax = [25, 0, 1]
leading_proton_softmax = [25.0, 0.8, 1.0]

[sys.statistical]
type = 'stats'
group = ['total',]

[sys.cohnoise]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_cohnoise.log'
nboots = 1000
nuniverses = 1000

[sys.intnoise]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_intnoise.log'
nboots = 1000
nuniverses = 1000

[sys.recombination]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_recombination.log'
nboots = 1000
nuniverses = 1000

[sys.signal_shape]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_sigshape.log'
nboots = 1000
nuniverses = 1000

[sys.GENIEReWeight_ICARUS_v2_multisim_ZExpAVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 52

[sys.GENIEReWeight_ICARUS_v2_multisim_RPA_CCQE]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 53

[sys.GENIEReWeight_ICARUS_v2_multisim_CoulombCCQE]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 54

[sys.GENIEReWeight_ICARUS_v2_multisim_NormCCMEC]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 55

[sys.GENIEReWeight_ICARUS_v2_multisim_NormNCMEC]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 56

[sys.GENIEReWeight_ICARUS_v2_multisim_NCELVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 57

[sys.GENIEReWeight_ICARUS_v2_multisim_CCRESVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 58

[sys.GENIEReWeight_ICARUS_v2_multisim_NCRESVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 59

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 60

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 61

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 62

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 63

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 64

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 65

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 66

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 67

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 68

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 69

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 70

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 71

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 72

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 73

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC1pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 74

[sys.GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC2pi]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 75

[sys.GENIEReWeight_ICARUS_v2_multisim_RDecBR1gamma]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 76

[sys.GENIEReWeight_ICARUS_v2_multisim_RDecBR1eta]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 77

[sys.GENIEReWeight_ICARUS_v2_multisim_COHVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 78

[sys.GENIEReWeight_ICARUS_v2_multisim_DISBYVariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 79

[sys.GENIEReWeight_ICARUS_v2_multisim_FSI_pi_VariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 80

[sys.GENIEReWeight_ICARUS_v2_multisim_FSI_N_VariationResponse]
type = 'multisim'
group = ['genie', 'reweightable', 'total_nostat', 'total']
index = 81

[sys.expskin_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 115

[sys.horncurrent_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 116

[sys.kminus_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 117

[sys.kplus_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 118

[sys.kzero_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 119

[sys.nucleoninexsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 120

[sys.nucleonqexsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 121

[sys.nucleontotxsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 122

[sys.piminus_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 123

[sys.pioninexsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 124

[sys.pionqexsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 125

[sys.piontotxsec_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 126

[sys.piplus_Flux]
type = 'multisim'
group = ['flux', 'reweightable', 'total_nostat', 'total']
index = 127